/**
 * This class is generated by jOOQ
 */
package models;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<models.tables.records.UrlsRecord, java.lang.Integer> IDENTITY_URLS = Identities0.IDENTITY_URLS;
	public static final org.jooq.Identity<models.tables.records.HitsRecord, java.lang.Integer> IDENTITY_HITS = Identities0.IDENTITY_HITS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<models.tables.records.UrlsRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
	public static final org.jooq.UniqueKey<models.tables.records.HitsRecord> CONSTRAINT_21 = UniqueKeys0.CONSTRAINT_21;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<models.tables.records.HitsRecord, models.tables.records.UrlsRecord> CONSTRAINT_21D = ForeignKeys0.CONSTRAINT_21D;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<models.tables.records.UrlsRecord, java.lang.Integer> IDENTITY_URLS = createIdentity(models.tables.Urls.URLS, models.tables.Urls.URLS.ID);
		public static org.jooq.Identity<models.tables.records.HitsRecord, java.lang.Integer> IDENTITY_HITS = createIdentity(models.tables.Hits.HITS, models.tables.Hits.HITS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<models.tables.records.UrlsRecord> CONSTRAINT_2 = createUniqueKey(models.tables.Urls.URLS, models.tables.Urls.URLS.ID);
		public static final org.jooq.UniqueKey<models.tables.records.HitsRecord> CONSTRAINT_21 = createUniqueKey(models.tables.Hits.HITS, models.tables.Hits.HITS.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<models.tables.records.HitsRecord, models.tables.records.UrlsRecord> CONSTRAINT_21D = createForeignKey(models.Keys.CONSTRAINT_2, models.tables.Hits.HITS, models.tables.Hits.HITS.URL_ID);
	}
}
