/**
 * This class is generated by jOOQ
 */
package models;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_3684A6F3_B310_4FC4_A10E_36BA211E67B5</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_3684A6F3_B310_4FC4_A10E_36BA211E67B5 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_3684A6F3_B310_4FC4_A10E_36BA211E67B5", models.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_83B671A7_7A89_49EA_A377_45C8E423B980</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_83B671A7_7A89_49EA_A377_45C8E423B980 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_83B671A7_7A89_49EA_A377_45C8E423B980", models.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
