/**
 * This class is generated by jOOQ
 */
package models;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.URLS
	 */
	public static final models.tables.Urls URLS = models.tables.Urls.URLS;

	/**
	 * The table PUBLIC.HITS
	 */
	public static final models.tables.Hits HITS = models.tables.Hits.HITS;
}
