/**
 * This class is generated by jOOQ
 */
package models.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Urls extends org.jooq.impl.TableImpl<models.tables.records.UrlsRecord> {

	private static final long serialVersionUID = -1221441430;

	/**
	 * The singleton instance of <code>PUBLIC.URLS</code>
	 */
	public static final models.tables.Urls URLS = new models.tables.Urls();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<models.tables.records.UrlsRecord> getRecordType() {
		return models.tables.records.UrlsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.URLS.ID</code>.
	 */
	public final org.jooq.TableField<models.tables.records.UrlsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.URLS.URL</code>.
	 */
	public final org.jooq.TableField<models.tables.records.UrlsRecord, java.lang.String> URL = createField("URL", org.jooq.impl.SQLDataType.VARCHAR.length(1500).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.URLS.CREATED_AT</code>.
	 */
	public final org.jooq.TableField<models.tables.records.UrlsRecord, java.sql.Timestamp> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>PUBLIC.URLS</code> table reference
	 */
	public Urls() {
		this("URLS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.URLS</code> table reference
	 */
	public Urls(java.lang.String alias) {
		this(alias, models.tables.Urls.URLS);
	}

	private Urls(java.lang.String alias, org.jooq.Table<models.tables.records.UrlsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Urls(java.lang.String alias, org.jooq.Table<models.tables.records.UrlsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, models.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<models.tables.records.UrlsRecord, java.lang.Integer> getIdentity() {
		return models.Keys.IDENTITY_URLS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<models.tables.records.UrlsRecord> getPrimaryKey() {
		return models.Keys.CONSTRAINT_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<models.tables.records.UrlsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<models.tables.records.UrlsRecord>>asList(models.Keys.CONSTRAINT_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public models.tables.Urls as(java.lang.String alias) {
		return new models.tables.Urls(alias, this);
	}

	/**
	 * Rename this table
	 */
	public models.tables.Urls rename(java.lang.String name) {
		return new models.tables.Urls(name, null);
	}
}
